# Generated by Django 2.2.6 on 2019-10-26 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('par', models.PositiveIntegerField()),
                ('low_score', models.PositiveIntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_2_name', models.CharField(max_length=100)),
                ('player_3_name', models.CharField(max_length=100)),
                ('player_4_name', models.CharField(max_length=100)),
                ('player_1_score', models.IntegerField(default=0)),
                ('player_2_score', models.IntegerField(default=0)),
                ('player_3_score', models.IntegerField(default=0)),
                ('player_4_score', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('present_hole', models.PositiveIntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='g_golf.Course')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('par', models.PositiveIntegerField()),
                ('low_score', models.PositiveIntegerField()),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hole_Inst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('player_1_score', models.CharField(max_length=100)),
                ('player_2_score', models.CharField(max_length=100)),
                ('player_3_score', models.CharField(max_length=100)),
                ('player_4_score', models.CharField(max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='g_golf.Game')),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='g_golf.Hole')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='hole_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_1', to='g_golf.Hole'),
        ),
        migrations.AddField(
            model_name='course',
            name='hole_10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_10', to='g_golf.Hole'),
        ),
        migrations.AddField(
            model_name='course',
            name='hole_11',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_11', to='g_golf.Hole'),
        ),
        migrations.AddField(
            model_name='course',
            name='hole_12',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_12', to='g_golf.Hole'),
        ),
        migrations.AddField(
            model_name='course',
            name='hole_13',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_13', to='g_golf.Hole'),
        ),
        migrations.AddField(
            model_name='course',
            name='hole_14',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_14', to='g_golf.Hole'),
        ),
        migrations.AddField(
            model_name='course',
            name='hole_15',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_15', to='g_golf.Hole'),
        ),
        migrations.AddField(
            model_name='course',
            name='hole_16',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_16', to='g_golf.Hole'),
        ),
        migrations.AddField(
            model_name='course',
            name='hole_17',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_17', to='g_golf.Hole'),
        ),
        migrations.AddField(
            model_name='course',
            name='hole_18',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_18', to='g_golf.Hole'),
        ),
        migrations.AddField(
            model_name='course',
            name='hole_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_2', to='g_golf.Hole'),
        ),
        migrations.AddField(
            model_name='course',
            name='hole_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_3', to='g_golf.Hole'),
        ),
        migrations.AddField(
            model_name='course',
            name='hole_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_4', to='g_golf.Hole'),
        ),
        migrations.AddField(
            model_name='course',
            name='hole_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_5', to='g_golf.Hole'),
        ),
        migrations.AddField(
            model_name='course',
            name='hole_6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_6', to='g_golf.Hole'),
        ),
        migrations.AddField(
            model_name='course',
            name='hole_7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_7', to='g_golf.Hole'),
        ),
        migrations.AddField(
            model_name='course',
            name='hole_8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_8', to='g_golf.Hole'),
        ),
        migrations.AddField(
            model_name='course',
            name='hole_9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_9', to='g_golf.Hole'),
        ),
    ]
