# Generated by Django 2.2.6 on 2019-10-26 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('g_golf', '0002_auto_20191026_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='hole_10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hole_10', to='g_golf.Hole'),
        ),
        migrations.AlterField(
            model_name='course',
            name='hole_11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hole_11', to='g_golf.Hole'),
        ),
        migrations.AlterField(
            model_name='course',
            name='hole_12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hole_12', to='g_golf.Hole'),
        ),
        migrations.AlterField(
            model_name='course',
            name='hole_13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hole_13', to='g_golf.Hole'),
        ),
        migrations.AlterField(
            model_name='course',
            name='hole_14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hole_14', to='g_golf.Hole'),
        ),
        migrations.AlterField(
            model_name='course',
            name='hole_15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hole_15', to='g_golf.Hole'),
        ),
        migrations.AlterField(
            model_name='course',
            name='hole_16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hole_16', to='g_golf.Hole'),
        ),
        migrations.AlterField(
            model_name='course',
            name='hole_17',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hole_17', to='g_golf.Hole'),
        ),
        migrations.AlterField(
            model_name='course',
            name='hole_18',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hole_18', to='g_golf.Hole'),
        ),
        migrations.AlterField(
            model_name='course',
            name='hole_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hole_2', to='g_golf.Hole'),
        ),
        migrations.AlterField(
            model_name='course',
            name='hole_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hole_3', to='g_golf.Hole'),
        ),
        migrations.AlterField(
            model_name='course',
            name='hole_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hole_4', to='g_golf.Hole'),
        ),
        migrations.AlterField(
            model_name='course',
            name='hole_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hole_5', to='g_golf.Hole'),
        ),
        migrations.AlterField(
            model_name='course',
            name='hole_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hole_6', to='g_golf.Hole'),
        ),
        migrations.AlterField(
            model_name='course',
            name='hole_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hole_7', to='g_golf.Hole'),
        ),
        migrations.AlterField(
            model_name='course',
            name='hole_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hole_8', to='g_golf.Hole'),
        ),
        migrations.AlterField(
            model_name='course',
            name='hole_9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hole_9', to='g_golf.Hole'),
        ),
    ]
