# Generated by Django 2.2.6 on 2019-10-27 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g_golf', '0005_hats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hats',
        ),
    ]
