# Generated by Django 2.2.6 on 2019-10-29 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('g_golf', '0008_auto_20191029_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hole',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
