# Generated by Django 2.2.6 on 2019-11-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_golf', '0011_game_player_1_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player_2_name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_3_name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_4_name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
